version: '3'
services:
  server:
    build: ./server
    restart: ${RESTART_POLICY}
    ports:
      - "${SERVER_PORT}:80"
    environment:
      - PORT=80
      - NODE_ENV=${NODE_ENV}
      - ORIGIN=${CLIENT_URL}

  client:
    build: ./client
    restart: ${RESTART_POLICY}
    ports:
      - "${CLIENT_PORT}:80"
    environment:
      - PORT=81
      - NODE_ENV=${NODE_ENV}
      - VUE_APP_SERVER=${SERVER_URL}
      - VUE_APP_PRIMARY_COLOR=${PRIMARY_COLOR}
    links:
      - server
